@echo off
echo Creating virtual environment...
python -m venv ..\..\venv_quiz
echo Activating and installing...
call ..\..\venv_quiz\Scripts\activate.bat
pip install -r requirements.txt
echo Starting app...
python app.py
